# Travis CI configuration for Django Project

language: python
sudo: required
python:
  - "3.4"
  - "3.5"
services:
  - mysql
env:
  -DJANGO=2.1 DB=mysql
install:
  - make deps
before_script:
    #- mysql -e 'create database cheapies;' -u root
  - make deploy
script:
  - python manage.py test
