# Travis CI configuration for Django Project

language: python
sudo: true
python:
  - "3.4"
  - "3.5"
services:
  - mysql
env:
  -DJANGO=2.1 DB=mysql
install:
  - pip install -r requirements.txt
  - apt-get install libgdal-dev
before_script:
  - mysql -e 'create database cheapies;' -u root
  - python3 manage.py makemigrations
  - python3 manage.py migrate
script:
  - python manage.py test
