# Travis CI configuration for Django Project

language: python
sudo: required
python:
  - "3.4"
  - "3.5"
services:
  - mysql
env:
  -DJANGO=2.1 DB=mysql
install:
  - pip install -r requirements.txt
  - sudo apt-get install -y libgdal-dev python3-gdal
before_script:
  - mysql -e 'create database cheapies;' -u root
  - python manage.py geoip_update
script:
  - python manage.py test
