version: "2"
services:
  django:
    container_name: django_server
    build:
      context: .
      dockerfile: Dockerfile
    image: cheapies
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/cheapies
    ports:
      - "8000:8000"

DATABASE_URL=mysql://root:itsasecret@db:3306/cheapies
  db:
    container_name: mysql_database
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=itsasecret
    volumes:
      - /Users/Adam/Development/data/mysql:/var/lib/mysql
